name: Node CI

on: [push, pull_request_target]

jobs:
    setupnode:
        name: Setup and Test NodeJs
        # needs: format
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install Prettier
              run: yarn workspace @project/react-app add prettier --ignore-platform

            - name: Check Formatting
              run: yarn run react-app:lint
